# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: golang:latest
stages:
  - build
  - test
build-main-app:
  stage: build
  script:
    - go install github.com/graipher/bluewalker
    - go install github.com/graipher/bluewalker/listener
run-tests:
  stage: test
  script:
    - go test -race -coverprofile=.cov.out github.com/graipher/bluewalker/...
    - go tool cover -func .cov.out
check-min-version:
  image: golang:1.15
  stage: test
  script:
    - go install github.com/graipher/bluewalker
    - go test github.com/graipher/bluewalker/...
sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
