image: golang:alpine

stages:
  - build
  - test

before_script:
  - mkdir -p /go/src/gitlab.com/jtaimisto
  - cp -a $(pwd) /go/src/gitlab.com/jtaimisto/bluewalker
  - apk add --no-cache git
  - go get golang.org/x/sys/unix
 
build-main-app:
  stage: build
  script:
    - cd /go/
    - go install gitlab.com/jtaimisto/bluewalker
    - go install gitlab.com/jtaimisto/bluewalker/listener

run-tests:
  stage: test
  script:
   - cd /go/
   - CGO_ENABLED=0 go test gitlab.com/jtaimisto/bluewalker...
